// auth.js
export const SET_NAME = 'SET_NAME';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_TOKEN = 'SET_TOKEN';
export const ATTEMPT_LOGIN = 'ATTEMPT_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const ATTEMPT_LOGOUT = 'ATTEMPT_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const ATTEMPT_REGISTER = 'ATTEMPT_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const RESET_REGISTER_FORM = 'RESET_REGISTER_FORM';
export const RESET_LOGIN_FORM = 'RESET_LOGIN_FORM';
export const TOGGLE_VIEW_USER = 'TOGGLE_VIEW_USER';

// items.js
export const FETCH_ITEMS = 'FETCH_ITEMS';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';
export const FETCH_CAPTURED_ITEM_SUCCESS = 'FETCH_CAPTURED_ITEM_SUCCESS';
export const FETCH_CAPTURED_ITEM_FAILURE = 'FETCH_CAPTURED_ITEM_FAILURE';
export const TOGGLE_SAVE_ITEM = 'TOGGLE_SAVE_ITEM';
export const SAVE_ITEM = 'SAVE_ITEM';
export const SAVE_ITEM_SUCCESS = 'SAVE_ITEM_SUCCESS';
export const SAVE_ITEM_FAILURE = 'SAVE_ITEM_FAILURE';
export const SORT_ITEMS = 'SORT_ITEMS';
export const TOGGLE_EDIT_ITEM = 'TOGGLE_EDIT_ITEM';
export const SET_ITEM_LIST_NAME = 'SET_ITEM_LIST_NAME';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE';
export const EDIT_ITEM = 'EDIT_ITEM';
export const EDIT_ITEM_SUCCESS = 'EDIT_ITEM_SUCCESS';
export const EDIT_ITEM_FAILURE = 'EDIT_ITEM_FAILURE';

// lists.js
export const FETCH_LISTS = 'FETCH_LISTS';
export const FETCH_LISTS_SUCCESS = 'FETCH_LISTS_SUCCESS';
export const FETCH_LISTS_FAILURE = 'FETCH_LISTS_FAILURE';
export const TOGGLE_CREATE_LIST = 'TOGGLE_CREATE_LIST';
export const CREATE_LIST = 'CREATE_LIST';
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS';
export const CREATE_LIST_FAILURE = 'CREATE_LIST_FAILURE';
export const RESET_CREATE_LIST_FORM = 'RESET_CREATE_LIST_FORM';
export const SET_LIST = 'SET_LIST';
export const SET_LIST_NAME = 'SET_LIST_NAME';
export const TOGGLE_SORT_LISTS = 'TOGGLE_SORT_LISTS';
export const TOGGLE_SORT_LIST_ITEMS = 'TOGGLE_SORT_LIST_ITEMS';
export const TOGGLE_EDIT_LIST = 'TOGGLE_EDIT_LIST';
export const EDIT_LIST = 'EDIT_LIST';
export const EDIT_LIST_SUCCESS = 'EDIT_LIST_SUCCESS';
export const EDIT_LIST_FAILURE = 'EDIT_LIST_FAILURE';
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';
export const DELETE_LIST_FAILURE = 'DELETE_LIST_FAILURE';
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';
export const FETCH_LIST_FAILURE = 'FETCH_LIST_FAILURE';

// stores.js
export const FETCH_STORES_SUCCESS = 'FETCH_STORES_SUCCESS';
export const FETCH_STORES_FAILURE = 'FETCH_STORES_FAILURE';
